# Generated by Django 4.2 on 2023-05-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='A short description of company or individual'),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acount_settings', to='accounts.account'),
        ),
    ]
