# Generated by Django 4.2 on 2023-09-19 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="phones_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountsettings",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_settings",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="industry",
            field=models.ManyToManyField(
                blank=True, related_name="accounts", to="accounts.industry"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="user_accounts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="phone",
            constraint=models.UniqueConstraint(
                fields=("account", "phone_number"), name="unique_account_phone_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="email",
            constraint=models.UniqueConstraint(
                fields=("account", "email_address"), name="unique_account_email_address"
            ),
        ),
    ]
